from __future__ import annotations
from typing import Any
from ..compat import *

class WindowSetupMixin:

    def init_ui(self) -> None:
        """Initialize ui."""
        central_widget = QWidget()
        self.setCentralWidget(central_widget)
        root_layout = QVBoxLayout(central_widget)
        self._setup_window_shell(root_layout)
        self._init_dashboard_page()
        self._init_additional_pages()
        self._register_navigation_pages()
        self._start_clock_timer()

    def _setup_window_shell(self, root_layout: Any) -> None:
        """Handle setup window shell."""
        self.top_bar = QHBoxLayout()
        self.time_label = QLabel('--:--')
        self.set_theme_role(self.time_label, 'section_title')
        self._pages = {}
        self.btn_page1 = QPushButton('Dashboard')
        self.btn_page1.setCheckable(True)
        self.btn_page1.setChecked(True)
        self.btn_page2 = QPushButton('Fundamentals')
        self.btn_page2.setCheckable(True)
        self.btn_page3 = QPushButton('News')
        self.btn_page3.setCheckable(True)
        self.btn_page4 = QPushButton('Portfolio')
        self.btn_page4.setCheckable(True)
        self.btn_page5 = QPushButton('Options Chain')
        self.btn_page5.setCheckable(True)
        self.btn_page13 = QPushButton('ETF')
        self.btn_page13.setCheckable(True)
        self.btn_page14 = QPushButton('Pre-Market')
        self.btn_page14.setCheckable(True)
        self.btn_page6 = QPushButton('Personal Finance')
        self.btn_page6.setCheckable(True)
        self.btn_page7 = QPushButton('Calendar')
        self.btn_page7.setCheckable(True)
        self.btn_page8 = QPushButton('Sectors')
        self.btn_page8.setCheckable(True)
        self.btn_page15 = QPushButton('Politics')
        self.btn_page15.setCheckable(True)
        self.btn_page9 = QPushButton('Settings')
        self.btn_page9.setCheckable(True)
        self.btn_page10 = QPushButton('Charts')
        self.btn_page10.setCheckable(True)
        self.btn_page11 = QPushButton('Multi Charts')
        self.btn_page11.setCheckable(True)
        self.btn_page12 = QPushButton('Stocks')
        self.btn_page12.setCheckable(True)
        self._nav_buttons = [
            self.btn_page1,
            self.btn_page4,
            self.btn_page6,
            self.btn_page7,
            self.btn_page3,
            self.btn_page8,
            self.btn_page12,
            self.btn_page2,
            self.btn_page10,
            self.btn_page11,
            self.btn_page5,
            self.btn_page13,
            self.btn_page14,
            self.btn_page15,
            self.btn_page9,
        ]
        refresh_btn = QPushButton('Refresh')
        refresh_btn.clicked.connect(lambda checked=False: self.refresh_data(force=True))
        snap_btn = QPushButton('Screenshot')
        snap_btn.clicked.connect(self.take_screenshot)

        nav_scroll_left = QPushButton('<')
        nav_scroll_left.setFixedWidth(24)
        nav_scroll_left.setFixedHeight(38)
        nav_scroll_right = QPushButton('>')
        nav_scroll_right.setFixedWidth(24)
        nav_scroll_right.setFixedHeight(38)

        nav_container = QWidget()
        nav_container_layout = QHBoxLayout(nav_container)
        nav_container_layout.setContentsMargins(0, 0, 0, 0)
        nav_container_layout.setSpacing(4)
        for button in self._nav_buttons:
            button.setMinimumHeight(38)
            button.setMinimumWidth(110)
            nav_container_layout.addWidget(button)

        self._nav_scroll_area = QScrollArea()
        self._nav_scroll_area.setWidget(nav_container)
        self._nav_scroll_area.setWidgetResizable(False)
        self._nav_scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self._nav_scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self._nav_scroll_area.setFrameShape(QFrame.Shape.NoFrame)
        self._nav_scroll_area.setFixedHeight(42)

        nav_scroll_left.clicked.connect(lambda: self._nav_scroll_area.horizontalScrollBar().setValue(
            self._nav_scroll_area.horizontalScrollBar().value() - 200))
        nav_scroll_right.clicked.connect(lambda: self._nav_scroll_area.horizontalScrollBar().setValue(
            self._nav_scroll_area.horizontalScrollBar().value() + 200))

        self.top_bar.addWidget(nav_scroll_left)
        self.top_bar.addWidget(self._nav_scroll_area, 1)
        self.top_bar.addWidget(nav_scroll_right)
        self._tab_picker_items = []
        self._tab_picker_map = {}
        self._tab_picker_popup = QDialog(self, Qt.WindowType.Popup | Qt.WindowType.FramelessWindowHint)
        self._tab_picker_popup.setModal(False)
        self._tab_picker_popup.setObjectName('tabPickerPopup')
        self._tab_picker_popup.setFixedWidth(300)
        popup_layout = QVBoxLayout(self._tab_picker_popup)
        popup_layout.setContentsMargins(10, 10, 10, 10)
        popup_layout.setSpacing(8)
        self._tab_picker_input = QLineEdit()
        self._tab_picker_input.setPlaceholderText('Type a tab name')
        self._tab_picker_input.textChanged.connect(self._filter_tab_picker_items)
        self._tab_picker_input.installEventFilter(self)
        popup_layout.addWidget(self._tab_picker_input)
        self._tab_picker_list = QListWidget()
        self._tab_picker_list.setMinimumHeight(220)
        self._tab_picker_list.setMaximumHeight(220)
        self._tab_picker_list.itemActivated.connect(self._activate_tab_picker_item)
        self._tab_picker_list.itemClicked.connect(self._activate_tab_picker_item)
        self._tab_picker_list.installEventFilter(self)
        popup_layout.addWidget(self._tab_picker_list)
        self._tab_picker_popup.installEventFilter(self)
        self._nav_prev_shortcut = QShortcut(QKeySequence(Qt.Key.Key_Left), self)
        self._nav_prev_shortcut.setContext(Qt.ShortcutContext.ApplicationShortcut)
        self._nav_prev_shortcut.activated.connect(lambda: self._handle_main_tab_arrow_shortcut(-1))
        self._nav_next_shortcut = QShortcut(QKeySequence(Qt.Key.Key_Right), self)
        self._nav_next_shortcut.setContext(Qt.ShortcutContext.ApplicationShortcut)
        self._nav_next_shortcut.activated.connect(lambda: self._handle_main_tab_arrow_shortcut(1))
        self._tab_picker_shortcut = QShortcut(QKeySequence('`'), self)
        self._tab_picker_shortcut.setContext(Qt.ShortcutContext.ApplicationShortcut)
        self._tab_picker_shortcut.activated.connect(self._handle_tab_picker_shortcut)
        self.tz_combo = QComboBox()
        self.tz_combo.setFixedWidth(120)
        self._tz_choices = TIMEZONE_CHOICES
        for name, _ in self._tz_choices:
            self.tz_combo.addItem(name)
        self.tz_combo.currentIndexChanged.connect(self.update_time)
        self._time_12h = load_time_format()
        self.time_fmt_btn = QPushButton('12h' if self._time_12h else '24h')
        self.time_fmt_btn.setCheckable(True)
        self.time_fmt_btn.setChecked(self._time_12h)
        self.time_fmt_btn.setFixedWidth(46)
        self.time_fmt_btn.setFixedHeight(26)
        self.time_fmt_btn.clicked.connect(self._toggle_time_format)
        self.top_bar.addWidget(self.tz_combo)
        self.top_bar.addWidget(self.time_label)
        self.top_bar.addWidget(self.time_fmt_btn)
        self.top_bar.addSpacing(8)
        self.top_bar.addWidget(refresh_btn)
        self.top_bar.addWidget(snap_btn)
        root_layout.addLayout(self.top_bar)
        self.stacked_widget = QStackedWidget()
        root_layout.addWidget(self.stacked_widget)
        footer_row = QHBoxLayout()
        self.status_bar = QLabel('Ready')
        self.set_theme_role(self.status_bar, 'status_muted')
        self.data_collection_label = QLabel('Data collected: awaiting first refresh')
        self.set_theme_role(self.data_collection_label, 'status_muted')
        self.data_collection_label.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter)
        footer_row.addWidget(self.status_bar, 1)
        footer_row.addWidget(self.data_collection_label, 0)
        root_layout.addLayout(footer_row)

    def _init_dashboard_page(self) -> None:
        """Handle init dashboard page."""
        self.page1 = QWidget()
        self.stacked_widget.addWidget(self.page1)
        main_layout = QHBoxLayout(self.page1)
        self.dashboard_main_splitter = QSplitter(Qt.Orientation.Horizontal)
        left_widget = QWidget()
        left_widget.setMinimumWidth(0)
        left_col = QVBoxLayout(left_widget)
        left_col.setContentsMargins(0, 0, 0, 0)
        left_col.setSpacing(8)
        self.ticker_input = QLineEdit()
        self.ticker_input.setPlaceholderText('Enter Ticker (e.g. AAPL)')
        self.ticker_input.returnPressed.connect(self.add_ticker)
        add_btn = QPushButton('Add')
        self.set_theme_variant(add_btn, 'accent')
        add_btn.clicked.connect(self.add_ticker)
        add_btn.setFixedHeight(24)
        self._dashboard_add_btn_refs = [add_btn]
        self.port_table = QTableWidget(0, 6)
        self.port_table.setHorizontalHeaderLabels(['Ticker', 'Price', 'Chg %', 'Weight', 'Gain $', ''])
        port_header = self.port_table.horizontalHeader()
        port_header.setSectionsMovable(True)
        port_header.setMinimumHeight(28)
        port_header.setDefaultSectionSize(28)
        port_header.setStretchLastSection(False)
        for index in range(5):
            port_header.setSectionResizeMode(index, QHeaderView.ResizeMode.Stretch)
        port_header.setSectionResizeMode(5, QHeaderView.ResizeMode.Fixed)
        self.port_table.setColumnWidth(5, 34)
        self.port_table.setMinimumWidth(0)
        self.port_table.verticalHeader().setVisible(False)
        self.port_table.verticalHeader().setDefaultSectionSize(24)
        self.port_table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.port_table.setSelectionMode(QTableWidget.SelectionMode.SingleSelection)
        self.port_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        self.port_table.cellClicked.connect(self._dashboard_on_portfolio_click)
        self.port_table.setAlternatingRowColors(True)
        if hasattr(self, '_dashboard_fit_portfolio_table_height'):
            self._dashboard_fit_portfolio_table_height()
        self.target_table = QTableWidget(0, 4)
        self.target_table.setHorizontalHeaderLabels(['Ticker', 'Current', 'Target', 'Upside (%)'])
        self.target_table.setMinimumWidth(0)
        self.target_table.horizontalHeader().setMinimumHeight(28)
        self.target_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.target_table.verticalHeader().setDefaultSectionSize(24)
        self.target_table.setAlternatingRowColors(True)
        self.target_table.setMaximumHeight(150)
        self.news_table = QTableWidget(0, 4)
        self.news_table.setHorizontalHeaderLabels(['Headline', 'Ticker', 'Source', 'Time'])
        self.news_table.setMinimumWidth(0)
        self.news_table.horizontalHeader().setSectionsMovable(True)
        self.news_table.horizontalHeader().setMinimumHeight(28)
        self.news_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.Stretch)
        for index in range(1, 4):
            self.news_table.horizontalHeader().setSectionResizeMode(index, QHeaderView.ResizeMode.ResizeToContents)
        self.news_table.setColumnHidden(1, True)
        self.news_table.setColumnHidden(2, True)
        self.news_table.setColumnHidden(3, True)
        self.news_table.verticalHeader().setDefaultSectionSize(24)
        self.news_table.setMaximumHeight(150)
        self.news_table.itemClicked.connect(self.open_news_link)
        portfolio_box = QFrame()
        portfolio_box.setMinimumWidth(0)
        self.set_theme_role(portfolio_box, 'panel')
        portfolio_layout = QVBoxLayout(portfolio_box)
        portfolio_layout.setContentsMargins(6, 6, 6, 6)
        portfolio_layout.setSpacing(4)
        port_header = QHBoxLayout()
        port_header.setContentsMargins(0, 0, 0, 0)
        port_header.setSpacing(6)
        self.port_header_lbl = QLabel('<b>My Portfolio</b>')
        self.port_header_lbl.setAlignment(Qt.AlignmentFlag.AlignLeft)
        self.port_header_lbl.setSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        self.set_theme_role(self.port_header_lbl, 'card_title')
        self.dashboard_portfolio_combo = QComboBox()
        self.dashboard_portfolio_combo.setMinimumWidth(0)
        self.dashboard_portfolio_combo.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        self.dashboard_portfolio_combo.currentIndexChanged.connect(self._dashboard_on_portfolio_changed)
        self.ticker_input.setMinimumWidth(0)
        self.ticker_input.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        add_btn.setSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        port_header.addWidget(self.port_header_lbl)
        port_header.addWidget(self.dashboard_portfolio_combo, 1)
        port_header.addWidget(self.ticker_input, 1)
        port_header.addWidget(add_btn)
        portfolio_layout.addLayout(port_header)
        portfolio_layout.addWidget(self.port_table)
        portfolio_layout.addStretch(1)
        targets_label = QLabel('<b>Analyst Price Targets</b>')
        self.set_theme_role(targets_label, 'section_title')
        news_label = QLabel('<b>Live News Feed</b>')
        self.set_theme_role(news_label, 'section_title')
        self.target_table.setMaximumHeight(16777215)
        self.news_table.setMaximumHeight(16777215)
        port_section = QWidget()
        port_section.setMinimumWidth(0)
        port_section.setSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Ignored)
        port_section_layout = QVBoxLayout(port_section)
        port_section_layout.setContentsMargins(0, 0, 0, 0)
        port_section_layout.setSpacing(0)
        port_section_layout.setAlignment(Qt.AlignmentFlag.AlignTop)
        port_section_layout.addWidget(portfolio_box)
        targets_section = QWidget()
        targets_section.setMinimumWidth(0)
        targets_section_layout = QVBoxLayout(targets_section)
        targets_section_layout.setContentsMargins(0, 0, 0, 0)
        targets_section_layout.setSpacing(4)
        targets_section_layout.addWidget(targets_label)
        targets_section_layout.addWidget(self.target_table)
        news_section = QWidget()
        news_section.setMinimumWidth(0)
        news_section_layout = QVBoxLayout(news_section)
        news_section_layout.setContentsMargins(0, 0, 0, 0)
        news_section_layout.setSpacing(4)
        news_section_layout.addWidget(news_label)
        news_section_layout.addWidget(self.news_table)
        self.dashboard_left_splitter = QSplitter(Qt.Orientation.Vertical)
        self.dashboard_left_splitter.setHandleWidth(6)
        self.dashboard_left_splitter.setStyleSheet(
            'QSplitter::handle { background: #2a2a4a; border-radius: 2px; }'
        )
        self.dashboard_left_splitter.addWidget(port_section)
        self.dashboard_left_splitter.addWidget(targets_section)
        self.dashboard_left_splitter.addWidget(news_section)
        self.dashboard_left_splitter.setStretchFactor(0, 3)
        self.dashboard_left_splitter.setStretchFactor(1, 2)
        self.dashboard_left_splitter.setStretchFactor(2, 2)
        self._p1_restore_left_splitter_sizes()
        self.dashboard_left_splitter.splitterMoved.connect(self._p1_on_left_splitter_moved)
        left_col.addWidget(self.dashboard_left_splitter)
        right_widget = QWidget()
        right_col = QVBoxLayout(right_widget)
        right_col.setContentsMargins(0, 0, 0, 0)
        indices_bar = QHBoxLayout()
        self.index_labels = {}
        for index_name in ['SPY', 'DXY', 'VIX', 'GLD', 'WTI']:
            label = QLabel(f'{index_name}: --')
            label.setFrameStyle(QFrame.Shape.Box | QFrame.Shadow.Raised)
            label.setMinimumWidth(120)
            label.setAlignment(Qt.AlignmentFlag.AlignCenter)
            self.set_theme_role(label, 'index')
            indices_bar.addWidget(label)
            self.index_labels[index_name] = label
        right_col.addLayout(indices_bar)
        timeframe_options = [('1 Minute', '7d', '1m'), ('5 Minutes', '60d', '5m'), ('15 Minutes', '60d', '15m'), ('1 Hour', '730d', '1h'), ('1 Day', '5y', '1d'), ('1 Week', '5y', '1wk'), ('1 Month', '5y', '1mo')]
        self.dashboard_timeframe_map = {label: (period, interval) for label, period, interval in timeframe_options}
        self.dashboard_symbol_input = QLineEdit(self.dashboard_chart_state.get('symbol', 'SPY'))
        self.dashboard_symbol_input.setPlaceholderText('Ticker')
        self.dashboard_symbol_input.setFixedWidth(110)
        self.dashboard_symbol_input.returnPressed.connect(self._dashboard_load_from_input)
        self.dashboard_load_btn = QPushButton('Load')
        self.set_theme_variant(self.dashboard_load_btn, 'accent')
        self.dashboard_load_btn.clicked.connect(self._dashboard_load_from_input)
        self.dashboard_export_options_btn = QPushButton('Export Top Options')
        self.set_theme_variant(self.dashboard_export_options_btn, 'accent')
        self.dashboard_export_options_btn.clicked.connect(self._dashboard_export_top_options)
        self.dashboard_refresh_btn = QPushButton('Refresh')
        self.set_theme_variant(self.dashboard_refresh_btn, 'accent')
        self.dashboard_refresh_btn.clicked.connect(self.refresh_data)
        self.dashboard_auto_btn = QPushButton('Auto')
        self.dashboard_auto_btn.setCheckable(True)
        self.dashboard_auto_btn.clicked.connect(self._dashboard_toggle_auto_follow)
        self.dashboard_timeframe_group = QButtonGroup(self)
        self.dashboard_timeframe_group.setExclusive(True)
        self.dashboard_timeframe_buttons = {}
        self.dashboard_indicator_buttons = {}
        self.dashboard_option_tables = {}

        toolbar = QHBoxLayout()
        toolbar_title = QLabel('<b>Dashboard Chart</b>')
        self.set_theme_role(toolbar_title, 'page_title')
        toolbar.addWidget(toolbar_title)
        toolbar.addSpacing(10)
        toolbar.addWidget(self.dashboard_symbol_input)
        toolbar.addWidget(self.dashboard_load_btn)
        toolbar.addWidget(self.dashboard_export_options_btn)
        toolbar.addSpacing(16)
        for label, _, _ in timeframe_options:
            btn = QPushButton(label)
            btn.setCheckable(True)
            btn.setMinimumHeight(26)
            btn.clicked.connect(partial(self._dashboard_set_timeframe, label))
            self.dashboard_timeframe_group.addButton(btn)
            self.dashboard_timeframe_buttons[label] = btn
            toolbar.addWidget(btn)
        toolbar.addStretch()
        toolbar.addWidget(self.dashboard_auto_btn)
        toolbar.addWidget(self.dashboard_refresh_btn)
        right_col.addLayout(toolbar)

        indicator_row = QHBoxLayout()
        indicator_label = QLabel('Indicators')
        self.set_theme_role(indicator_label, 'muted')
        indicator_row.addWidget(indicator_label)
        indicator_row.addSpacing(8)
        for name in ('Volume', 'RSI', '200 MA'):
            btn = QPushButton(name)
            btn.setCheckable(True)
            btn.clicked.connect(partial(self._dashboard_toggle_indicator, name))
            self.dashboard_indicator_buttons[name] = btn
            indicator_row.addWidget(btn)
        indicator_row.addStretch()
        right_col.addLayout(indicator_row)

        info_strip = QHBoxLayout()
        self.dashboard_symbol_label = QLabel(self.dashboard_chart_state.get('symbol', 'SPY'))
        self.dashboard_price_label = QLabel('--')
        self.dashboard_price_label.setMinimumHeight(30)
        self.dashboard_price_label.setMinimumWidth(92)
        self.dashboard_change_label = QLabel('--')
        self.dashboard_ohlc_label = QLabel('O --  H --  L --  C --')
        self.dashboard_status_label = QLabel('Ready')
        self.set_theme_role(self.dashboard_status_label, 'status_muted')
        info_strip.addWidget(self.dashboard_symbol_label)
        info_strip.addSpacing(16)
        info_strip.addWidget(self.dashboard_price_label)
        info_strip.addWidget(self.dashboard_change_label)
        info_strip.addSpacing(20)
        info_strip.addWidget(self.dashboard_ohlc_label, 1)
        info_strip.addWidget(self.dashboard_status_label)
        right_col.addLayout(info_strip)

        self.dashboard_body_splitter = QSplitter(Qt.Orientation.Horizontal)
        chart_container = QWidget()
        chart_layout = QVBoxLayout(chart_container)
        chart_layout.setContentsMargins(0, 0, 0, 0)
        chart_layout.setSpacing(6)
        self.dashboard_panels = QSplitter(Qt.Orientation.Vertical)
        self.dashboard_chart_axis = DateAxisItem(orientation='bottom')
        self.dashboard_main_plot = pg.PlotWidget(axisItems={'bottom': self.dashboard_chart_axis})
        self.dashboard_main_plot.showGrid(x=True, y=True, alpha=0.15)
        self.dashboard_main_plot.getPlotItem().setMenuEnabled(False)
        self.dashboard_main_plot.getPlotItem().hideAxis('left')
        self.dashboard_main_plot.getPlotItem().showAxis('right')
        self.dashboard_main_plot.getPlotItem().vb.sigXRangeChanged.connect(self._dashboard_on_x_range_changed)
        self.dashboard_main_plot.getPlotItem().vb.sigRangeChanged.connect(self._dashboard_refresh_overlay_positions)
        self.dashboard_volume_axis = DateAxisItem(orientation='bottom')
        self.dashboard_volume_plot = pg.PlotWidget(axisItems={'bottom': self.dashboard_volume_axis})
        self.dashboard_volume_plot.showGrid(x=True, y=False, alpha=0.1)
        self.dashboard_volume_plot.getPlotItem().setMenuEnabled(False)
        self.dashboard_volume_plot.getPlotItem().hideAxis('left')
        self.dashboard_volume_plot.getPlotItem().showAxis('right')
        self.dashboard_volume_plot.setMaximumHeight(160)
        self.dashboard_volume_plot.setXLink(self.dashboard_main_plot)
        self.dashboard_volume_plot.getPlotItem().vb.sigRangeChanged.connect(self._dashboard_refresh_overlay_positions)
        self.dashboard_rsi_axis = DateAxisItem(orientation='bottom')
        self.dashboard_rsi_plot = pg.PlotWidget(axisItems={'bottom': self.dashboard_rsi_axis})
        self.dashboard_rsi_plot.showGrid(x=True, y=True, alpha=0.1)
        self.dashboard_rsi_plot.getPlotItem().setMenuEnabled(False)
        self.dashboard_rsi_plot.getPlotItem().hideAxis('left')
        self.dashboard_rsi_plot.getPlotItem().showAxis('right')
        self.dashboard_rsi_plot.setMaximumHeight(160)
        self.dashboard_rsi_plot.setXLink(self.dashboard_main_plot)
        self.dashboard_rsi_plot.getPlotItem().vb.sigRangeChanged.connect(self._dashboard_refresh_overlay_positions)
        self.dashboard_panels.addWidget(self.dashboard_main_plot)
        self.dashboard_panels.addWidget(self.dashboard_volume_plot)
        self.dashboard_panels.addWidget(self.dashboard_rsi_plot)
        self.dashboard_panels.setStretchFactor(0, 6)
        self.dashboard_panels.setStretchFactor(1, 2)
        self.dashboard_panels.setStretchFactor(2, 2)
        chart_layout.addWidget(self.dashboard_panels, 1)
        self.dashboard_body_splitter.addWidget(chart_container)

        options_sidebar = QWidget()
        options_layout = QVBoxLayout(options_sidebar)
        options_layout.setContentsMargins(0, 0, 0, 0)
        options_layout.setSpacing(8)
        for bucket_key, bucket_title in (
            ('0_week', 'Top Options by Volume - 0 Week'),
            ('2_weeks', 'Top Options by Volume - 2 Weeks'),
            ('4_weeks', 'Top Options by Volume - 4 Weeks'),
        ):
            bucket_label = QLabel(bucket_title)
            self.set_theme_role(bucket_label, 'section_title')
            table = QTableWidget(0, 6)
            table.setHorizontalHeaderLabels(['Ticker', 'Type', 'Strike', 'Exp', 'Price', 'Vol'])
            table.horizontalHeader().setMinimumHeight(28)
            table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
            table.verticalHeader().setDefaultSectionSize(24)
            table.setAlternatingRowColors(True)
            options_layout.addWidget(bucket_label)
            options_layout.addWidget(table, 1)
            self.dashboard_option_tables[bucket_key] = table
        self.dashboard_body_splitter.addWidget(options_sidebar)
        self.dashboard_body_splitter.setStretchFactor(0, 5)
        self.dashboard_body_splitter.setStretchFactor(1, 2)
        self.dashboard_body_splitter.splitterMoved.connect(self._dashboard_on_splitter_moved)
        right_col.addWidget(self.dashboard_body_splitter, 1)
        self._dashboard_apply_splitter_sizes()
        self.dashboard_crosshair_proxy = pg.SignalProxy(self.dashboard_main_plot.scene().sigMouseMoved, rateLimit=30, slot=self._dashboard_on_mouse_moved)
        self._dashboard_refresh_portfolio_selector()
        self.dashboard_main_splitter.addWidget(left_widget)
        self.dashboard_main_splitter.addWidget(right_widget)
        self.dashboard_main_splitter.setStretchFactor(0, 3)
        self.dashboard_main_splitter.setStretchFactor(1, 5)
        self.dashboard_main_splitter.splitterMoved.connect(self._dashboard_on_main_splitter_moved)
        main_layout.addWidget(self.dashboard_main_splitter)
        self._dashboard_apply_main_splitter_sizes()

    def _init_additional_pages(self) -> None:
        """Handle init additional pages."""
        self.page4 = QWidget()
        self.stacked_widget.addWidget(self.page4)
        self.init_page4()
        self.page6 = QWidget()
        self.stacked_widget.addWidget(self.page6)
        self.init_page6()
        self.page7 = QWidget()
        self.stacked_widget.addWidget(self.page7)
        self.init_page7()
        self.page3 = QWidget()
        self.stacked_widget.addWidget(self.page3)
        self.init_page3()
        self.page8 = QWidget()
        self.stacked_widget.addWidget(self.page8)
        self.init_page8()
        self.page12 = QWidget()
        self.stacked_widget.addWidget(self.page12)
        self.init_page12()
        self.page2 = QWidget()
        self.stacked_widget.addWidget(self.page2)
        page2_layout = QVBoxLayout(self.page2)
        page2_layout.setContentsMargins(10, 10, 10, 10)
        self.init_page2(page2_layout)
        self.page10 = QWidget()
        self.stacked_widget.addWidget(self.page10)
        self.init_page10()
        self.page11 = QWidget()
        self.stacked_widget.addWidget(self.page11)
        self.init_page11()
        self.page5 = QWidget()
        self.stacked_widget.addWidget(self.page5)
        self.init_page5()
        self.page13 = QWidget()
        self.stacked_widget.addWidget(self.page13)
        self.init_page13()
        self.page14 = QWidget()
        self.stacked_widget.addWidget(self.page14)
        self.init_page14()
        self.page15 = QWidget()
        self.stacked_widget.addWidget(self.page15)
        self.init_page15()
        self.page9 = QWidget()
        self.stacked_widget.addWidget(self.page9)
        self.init_page9()

    def _apply_window_theme(self) -> None:
        """Apply the active theme to shared shell widgets and dashboard plots."""
        self.set_status_text(self.status_bar, self.status_bar.text(), status=self.status_bar.property('bt_status') or 'muted')
        self.set_status_text(self.data_collection_label, self.data_collection_label.text(), status=self.data_collection_label.property('bt_status') or 'muted')
        for plot in getattr(self, 'charts', []):
            self.style_plot_widget(plot)
