from __future__ import annotations
from typing import Any
from ..compat import *

class WindowSetupMixin:

    def init_ui(self) -> None:
        """Initialize ui."""
        central_widget = QWidget()
        self.setCentralWidget(central_widget)
        root_layout = QVBoxLayout(central_widget)
        self._setup_window_shell(root_layout)
        self._init_dashboard_page()
        self._init_additional_pages()
        self._register_navigation_pages()
        self._start_clock_timer()

    def _setup_window_shell(self, root_layout: Any) -> None:
        """Handle setup window shell."""
        self.top_bar = QHBoxLayout()
        self.time_label = QLabel('--:--')
        self._pages = {}
        self.btn_page1 = QPushButton('Dashboard')
        self.btn_page1.setCheckable(True)
        self.btn_page1.setChecked(True)
        self.btn_page2 = QPushButton('Fundamentals')
        self.btn_page2.setCheckable(True)
        self.btn_page3 = QPushButton('News')
        self.btn_page3.setCheckable(True)
        self.btn_page4 = QPushButton('Portfolio')
        self.btn_page4.setCheckable(True)
        self.btn_page5 = QPushButton('Options Chain')
        self.btn_page5.setCheckable(True)
        self.btn_page6 = QPushButton('Personal Finance')
        self.btn_page6.setCheckable(True)
        self.btn_page7 = QPushButton('Calendar')
        self.btn_page7.setCheckable(True)
        self.btn_page8 = QPushButton('Sectors')
        self.btn_page8.setCheckable(True)
        self.btn_page9 = QPushButton('Settings')
        self.btn_page9.setCheckable(True)
        self.btn_page10 = QPushButton('Charts')
        self.btn_page10.setCheckable(True)
        refresh_btn = QPushButton('Refresh')
        refresh_btn.clicked.connect(self.refresh_data)
        snap_btn = QPushButton('Screenshot')
        snap_btn.clicked.connect(self.take_screenshot)
        self._close_hold_timer = QTimer(self)
        self._close_hold_timer.setSingleShot(True)
        self._close_hold_timer.setInterval(2000)
        self._close_hold_timer.timeout.connect(self._on_close_hold_complete)
        self._close_btn = QPushButton('Close')
        self._close_btn.setStyleSheet('QPushButton { color: #ff5555; border: 1px solid #ff5555; border-radius: 4px; padding: 3px 8px; }QPushButton:pressed { background-color: #3a1a1a; }')
        self._close_btn.pressed.connect(lambda: self._close_hold_timer.start(2000))
        self._close_btn.released.connect(lambda: self._close_hold_timer.stop())
        for button in [self.btn_page1, self.btn_page4, self.btn_page6, self.btn_page7, self.btn_page3, self.btn_page8, self.btn_page10, self.btn_page2, self.btn_page5, self.btn_page9]:
            self.top_bar.addWidget(button)
        self.top_bar.addStretch()
        self._register_navigation_pages()
        self.tz_combo = QComboBox()
        self.tz_combo.setFixedWidth(120)
        self.tz_combo.setStyleSheet('QComboBox { font-size: 11px; }')
        self._tz_choices = TIMEZONE_CHOICES
        for name, _ in self._tz_choices:
            self.tz_combo.addItem(name)
        self.tz_combo.currentIndexChanged.connect(self.update_time)
        self.time_fmt_btn = QPushButton('24h')
        self.time_fmt_btn.setCheckable(True)
        self.time_fmt_btn.setFixedWidth(36)
        self.time_fmt_btn.setFixedHeight(22)
        self.time_fmt_btn.setStyleSheet('QPushButton { font-size: 11px; }')
        self._time_12h = False
        self.time_fmt_btn.clicked.connect(self._toggle_time_format)
        self.top_bar.addWidget(self.tz_combo)
        self.top_bar.addWidget(self.time_label)
        self.top_bar.addWidget(self.time_fmt_btn)
        self.top_bar.addSpacing(8)
        self.top_bar.addWidget(refresh_btn)
        self.top_bar.addWidget(snap_btn)
        self.top_bar.addWidget(self._close_btn)
        root_layout.addLayout(self.top_bar)
        self.stacked_widget = QStackedWidget()
        root_layout.addWidget(self.stacked_widget)
        footer_row = QHBoxLayout()
        self.status_bar = QLabel('Ready')
        self.status_bar.setStyleSheet('color: #888; font-size: 11px; padding: 2px;')
        self.data_collection_label = QLabel('Data collected: awaiting first refresh')
        self.data_collection_label.setStyleSheet('color: #888; font-size: 11px; padding: 2px;')
        self.data_collection_label.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter)
        footer_row.addWidget(self.status_bar, 1)
        footer_row.addWidget(self.data_collection_label, 0)
        root_layout.addLayout(footer_row)

    def _init_dashboard_page(self) -> None:
        """Handle init dashboard page."""
        self.page1 = QWidget()
        self.stacked_widget.addWidget(self.page1)
        main_layout = QHBoxLayout(self.page1)
        left_col = QVBoxLayout()
        left_col.setSpacing(8)
        self.ticker_input = QLineEdit()
        self.ticker_input.setPlaceholderText('Enter Ticker (e.g. AAPL)')
        self.ticker_input.returnPressed.connect(self.add_ticker)
        add_btn = QPushButton('Add')
        add_btn.clicked.connect(self.add_ticker)
        add_btn.setFixedHeight(24)
        self.port_table = QTableWidget(0, 7)
        self.port_table.setHorizontalHeaderLabels(['Ticker', 'Price', 'Chg $', 'Chg %', 'Weight', 'Gain $', ''])
        self.port_table.horizontalHeader().setSectionsMovable(True)
        self.port_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
        self.port_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
        self.port_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
        self.port_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
        self.port_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.ResizeToContents)
        self.port_table.horizontalHeader().setSectionResizeMode(5, QHeaderView.ResizeMode.Stretch)
        self.port_table.horizontalHeader().setSectionResizeMode(6, QHeaderView.ResizeMode.Fixed)
        self.port_table.setColumnWidth(6, 28)
        self.port_table.verticalHeader().setVisible(False)
        self.port_table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.port_table.setSelectionMode(QTableWidget.SelectionMode.NoSelection)
        self.port_table.setMaximumHeight(300)
        self.port_table.setStyleSheet('QTableWidget { background: #0d0d1f; border: 1px solid #333; border-radius: 4px; gridline-color: #24243a; }QHeaderView::section { background: #16162b; color: #aaa; border: 0; border-bottom: 1px solid #333; padding: 4px 6px; }')
        self.target_table = QTableWidget(0, 4)
        self.target_table.setHorizontalHeaderLabels(['Ticker', 'Current', 'Target', 'Upside (%)'])
        self.target_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.news_table = QTableWidget(0, 4)
        self.news_table.setHorizontalHeaderLabels(['Headline', 'Ticker', 'Source', 'Time'])
        self.news_table.horizontalHeader().setSectionsMovable(True)
        self.news_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.Stretch)
        for index in range(1, 4):
            self.news_table.horizontalHeader().setSectionResizeMode(index, QHeaderView.ResizeMode.ResizeToContents)
        self.news_table.itemClicked.connect(self.open_news_link)
        portfolio_box = QGroupBox()
        portfolio_box.setStyleSheet('QGroupBox { border: 1px solid #333; border-radius: 4px; margin-top: 0px; background: #121220; }')
        portfolio_layout = QVBoxLayout(portfolio_box)
        portfolio_layout.setContentsMargins(8, 8, 8, 8)
        portfolio_layout.setSpacing(6)
        port_header = QHBoxLayout()
        port_header.setContentsMargins(0, 0, 0, 0)
        port_header.setSpacing(6)
        self.port_header_lbl = QLabel('<b>My Portfolio</b>')
        self.port_header_lbl.setAlignment(Qt.AlignmentFlag.AlignLeft)
        self.port_header_lbl.setStyleSheet('color: #aaa; font-size: 12px;')
        self.ticker_input.setMinimumWidth(180)
        port_header.addWidget(self.port_header_lbl)
        port_header.addStretch()
        port_header.addWidget(self.ticker_input)
        port_header.addWidget(add_btn)
        portfolio_layout.addLayout(port_header)
        portfolio_layout.addWidget(self.port_table)
        left_col.addWidget(portfolio_box)
        left_col.addWidget(QLabel('<b>Analyst Price Targets</b>'))
        left_col.addWidget(self.target_table)
        left_col.addWidget(QLabel('<b>Live News Feed</b>'))
        left_col.addWidget(self.news_table)
        right_col = QVBoxLayout()
        indices_bar = QHBoxLayout()
        self.index_labels = {}
        for index_name in ['SPY', 'QQQ', 'VIX', 'GLD', 'WTI']:
            label = QLabel(f'{index_name}: --')
            label.setFrameStyle(QFrame.Shape.Box | QFrame.Shadow.Raised)
            label.setMinimumWidth(120)
            label.setAlignment(Qt.AlignmentFlag.AlignCenter)
            indices_bar.addWidget(label)
            self.index_labels[index_name] = label
        right_col.addLayout(indices_bar)
        self.charts = []
        self.date_axes = []
        self.chart_inputs = []
        self.timeframe_combos = []
        self.option_tables = []
        timeframe_options = [('1 Minute', '7d', '1m'), ('5 Minutes', '60d', '5m'), ('15 Minutes', '60d', '15m'), ('1 Hour', '730d', '1h'), ('1 Day', '5y', '1d'), ('1 Week', '5y', '1wk'), ('1 Month', '5y', '1mo')]
        for slot_index in range(3):
            row_layout = QHBoxLayout()
            chart_container = QVBoxLayout()
            control_row = QHBoxLayout()
            inp = QLineEdit(self.chart_slots[slot_index])
            inp.setFixedWidth(80)
            inp.returnPressed.connect(self.refresh_data)
            self.chart_inputs.append(inp)
            combo = QComboBox()
            for label, period, interval in timeframe_options:
                combo.addItem(label, (period, interval))
            combo.setCurrentIndex(5)
            combo.currentIndexChanged.connect(self.refresh_data)
            self.timeframe_combos.append(combo)
            control_row.addWidget(inp)
            control_row.addWidget(combo)
            control_row.addWidget(QLabel('Chart'))
            control_row.addStretch()
            date_axis = DateAxisItem(orientation='bottom')
            self.date_axes.append(date_axis)
            plot = pg.PlotWidget(axisItems={'bottom': date_axis})
            plot.setBackground('#0b1220')
            plot.setMouseEnabled(x=True, y=True)
            plot.getPlotItem().setMenuEnabled(False)
            plot.getPlotItem().hideAxis('left')
            plot.getPlotItem().showAxis('right')
            plot.getPlotItem().getAxis('right').setTextPen('#8b9cad')
            plot.getPlotItem().getAxis('bottom').setTextPen('#8b9cad')
            plot.setStyleSheet('border: 1px solid #1f2937; border-radius: 6px;')
            plot.showGrid(x=True, y=True, alpha=0.15)
            plot.getPlotItem().vb.sigXRangeChanged.connect(partial(self._dashboard_on_x_range_changed, slot_index))
            chart_container.addLayout(control_row)
            chart_container.addWidget(plot)
            self.charts.append(plot)
            opt_container = QVBoxLayout()
            opt_table = QTableWidget(0, 6)
            opt_table.setHorizontalHeaderLabels(['Ticker', 'Type', 'Strike', 'Exp', 'Price', 'Vol'])
            opt_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
            opt_container.addWidget(QLabel('Top Options by Volume'))
            opt_container.addWidget(opt_table)
            self.option_tables.append(opt_table)
            row_layout.addLayout(chart_container, 2)
            row_layout.addLayout(opt_container, 1)
            right_col.addLayout(row_layout)
        main_layout.addLayout(left_col, 1)
        main_layout.addLayout(right_col, 4)

    def _init_additional_pages(self) -> None:
        """Handle init additional pages."""
        self.page4 = QWidget()
        self.stacked_widget.addWidget(self.page4)
        self.init_page4()
        self.page6 = QWidget()
        self.stacked_widget.addWidget(self.page6)
        self.init_page6()
        self.page7 = QWidget()
        self.stacked_widget.addWidget(self.page7)
        self.init_page7()
        self.page3 = QWidget()
        self.stacked_widget.addWidget(self.page3)
        self.init_page3()
        self.page8 = QWidget()
        self.stacked_widget.addWidget(self.page8)
        self.init_page8()
        self.page10 = QWidget()
        self.stacked_widget.addWidget(self.page10)
        self.init_page10()
        self.page2 = QWidget()
        self.stacked_widget.addWidget(self.page2)
        page2_layout = QVBoxLayout(self.page2)
        page2_layout.setContentsMargins(10, 10, 10, 10)
        self.init_page2(page2_layout)
        self.page5 = QWidget()
        self.stacked_widget.addWidget(self.page5)
        self.init_page5()
        self.page9 = QWidget()
        self.stacked_widget.addWidget(self.page9)
        self.init_page9()
