"""Static, page-local Sectors universe sourced from issuer holdings snapshots.

The eleven standard groups use the top 20 holdings from their Select Sector
SPDR funds. Crypto uses the first 20 US-listed equities in BITQ, and Metals
uses XME's top 20 holdings. All source snapshots are dated 2026-07-09.
"""

from __future__ import annotations

from dataclasses import dataclass


SECTORS_PAGE_SOURCE_AS_OF = "2026-07-09"


@dataclass(frozen=True, slots=True)
class SectorConstituent:
    symbol: str
    name: str


def _constituents(*rows: tuple[str, str]) -> tuple[SectorConstituent, ...]:
    return tuple(SectorConstituent(symbol=symbol, name=name) for symbol, name in rows)


SECTORS_PAGE_DATA: dict[str, tuple[SectorConstituent, ...]] = {
    "Technology": _constituents(
        ("NVDA", "NVIDIA"),
        ("AAPL", "Apple"),
        ("MSFT", "Microsoft"),
        ("AVGO", "Broadcom"),
        ("AMD", "Advanced Micro Devices"),
        ("MU", "Micron Technology"),
        ("INTC", "Intel"),
        ("CSCO", "Cisco Systems"),
        ("AMAT", "Applied Materials"),
        ("LRCX", "Lam Research"),
        ("KLAC", "KLA"),
        ("PLTR", "Palantir Technologies"),
        ("TXN", "Texas Instruments"),
        ("IBM", "IBM"),
        ("SNDK", "Sandisk"),
        ("PANW", "Palo Alto Networks"),
        ("ORCL", "Oracle"),
        ("MRVL", "Marvell Technology"),
        ("CRWD", "CrowdStrike"),
        ("QCOM", "Qualcomm"),
    ),
    "Financials": _constituents(
        ("BRK-B", "Berkshire Hathaway Class B"),
        ("JPM", "JPMorgan Chase"),
        ("V", "Visa"),
        ("MA", "Mastercard"),
        ("BAC", "Bank of America"),
        ("GS", "Goldman Sachs"),
        ("MS", "Morgan Stanley"),
        ("WFC", "Wells Fargo"),
        ("C", "Citigroup"),
        ("AXP", "American Express"),
        ("SCHW", "Charles Schwab"),
        ("BLK", "BlackRock"),
        ("PGR", "Progressive"),
        ("SPGI", "S&P Global"),
        ("CB", "Chubb"),
        ("COF", "Capital One Financial"),
        ("BNY", "Bank of New York Mellon"),
        ("PNC", "PNC Financial Services"),
        ("USB", "U.S. Bancorp"),
        ("HOOD", "Robinhood Markets"),
    ),
    "Healthcare": _constituents(
        ("LLY", "Eli Lilly"),
        ("JNJ", "Johnson & Johnson"),
        ("ABBV", "AbbVie"),
        ("UNH", "UnitedHealth Group"),
        ("MRK", "Merck"),
        ("AMGN", "Amgen"),
        ("TMO", "Thermo Fisher Scientific"),
        ("GILD", "Gilead Sciences"),
        ("ABT", "Abbott Laboratories"),
        ("ISRG", "Intuitive Surgical"),
        ("PFE", "Pfizer"),
        ("CVS", "CVS Health"),
        ("VRTX", "Vertex Pharmaceuticals"),
        ("DHR", "Danaher"),
        ("BMY", "Bristol Myers Squibb"),
        ("SYK", "Stryker"),
        ("MDT", "Medtronic"),
        ("MCK", "McKesson"),
        ("ELV", "Elevance Health"),
        ("CI", "The Cigna Group"),
    ),
    "Consumer Cyclical": _constituents(
        ("AMZN", "Amazon"),
        ("TSLA", "Tesla"),
        ("HD", "Home Depot"),
        ("MCD", "McDonald's"),
        ("TJX", "TJX Companies"),
        ("BKNG", "Booking Holdings"),
        ("SBUX", "Starbucks"),
        ("LOW", "Lowe's"),
        ("MAR", "Marriott International"),
        ("HLT", "Hilton Worldwide"),
        ("DASH", "DoorDash"),
        ("RCL", "Royal Caribbean Cruises"),
        ("ROST", "Ross Stores"),
        ("ORLY", "O'Reilly Automotive"),
        ("GM", "General Motors"),
        ("ABNB", "Airbnb"),
        ("F", "Ford Motor"),
        ("EBAY", "eBay"),
        ("NKE", "Nike"),
        ("AZO", "AutoZone"),
    ),
    "Energy": _constituents(
        ("XOM", "Exxon Mobil"),
        ("CVX", "Chevron"),
        ("COP", "ConocoPhillips"),
        ("MPC", "Marathon Petroleum"),
        ("PSX", "Phillips 66"),
        ("VLO", "Valero Energy"),
        ("SLB", "SLB"),
        ("EOG", "EOG Resources"),
        ("WMB", "Williams Companies"),
        ("KMI", "Kinder Morgan"),
        ("TRGP", "Targa Resources"),
        ("BKR", "Baker Hughes"),
        ("OKE", "ONEOK"),
        ("DVN", "Devon Energy"),
        ("OXY", "Occidental Petroleum"),
        ("FANG", "Diamondback Energy"),
        ("EQT", "EQT"),
        ("HAL", "Halliburton"),
        ("TPL", "Texas Pacific Land"),
        ("EXE", "Expand Energy"),
    ),
    "Communication Services": _constituents(
        ("META", "Meta Platforms"),
        ("GOOGL", "Alphabet Class A"),
        ("GOOG", "Alphabet Class C"),
        ("TMUS", "T-Mobile US"),
        ("NFLX", "Netflix"),
        ("EA", "Electronic Arts"),
        ("LYV", "Live Nation Entertainment"),
        ("TTWO", "Take-Two Interactive"),
        ("WBD", "Warner Bros. Discovery"),
        ("DIS", "Walt Disney"),
        ("CMCSA", "Comcast"),
        ("T", "AT&T"),
        ("OMC", "Omnicom Group"),
        ("VZ", "Verizon Communications"),
        ("ECHO", "EchoStar"),
        ("TKO", "TKO Group Holdings"),
        ("CHTR", "Charter Communications"),
        ("FOXA", "Fox Class A"),
        ("NWSA", "News Corp Class A"),
        ("TTD", "The Trade Desk"),
    ),
    "Industrials": _constituents(
        ("CAT", "Caterpillar"),
        ("GE", "GE Aerospace"),
        ("GEV", "GE Vernova"),
        ("RTX", "RTX"),
        ("BA", "Boeing"),
        ("UNP", "Union Pacific"),
        ("ETN", "Eaton"),
        ("UBER", "Uber Technologies"),
        ("DE", "Deere"),
        ("VRT", "Vertiv Holdings"),
        ("PH", "Parker-Hannifin"),
        ("HWM", "Howmet Aerospace"),
        ("LMT", "Lockheed Martin"),
        ("TT", "Trane Technologies"),
        ("PWR", "Quanta Services"),
        ("ADP", "Automatic Data Processing"),
        ("GD", "General Dynamics"),
        ("CMI", "Cummins"),
        ("CSX", "CSX"),
        ("JCI", "Johnson Controls"),
    ),
    "Consumer Defensive": _constituents(
        ("WMT", "Walmart"),
        ("COST", "Costco Wholesale"),
        ("PG", "Procter & Gamble"),
        ("KO", "Coca-Cola"),
        ("PM", "Philip Morris International"),
        ("CL", "Colgate-Palmolive"),
        ("MO", "Altria Group"),
        ("MNST", "Monster Beverage"),
        ("PEP", "PepsiCo"),
        ("MDLZ", "Mondelez International"),
        ("TGT", "Target"),
        ("KDP", "Keurig Dr Pepper"),
        ("SYY", "Sysco"),
        ("ADM", "Archer-Daniels-Midland"),
        ("KVUE", "Kenvue"),
        ("KMB", "Kimberly-Clark"),
        ("KR", "Kroger"),
        ("CASY", "Casey's General Stores"),
        ("DG", "Dollar General"),
        ("HSY", "Hershey"),
    ),
    "Utilities": _constituents(
        ("NEE", "NextEra Energy"),
        ("SO", "Southern Company"),
        ("DUK", "Duke Energy"),
        ("CEG", "Constellation Energy"),
        ("AEP", "American Electric Power"),
        ("SRE", "Sempra"),
        ("D", "Dominion Energy"),
        ("ETR", "Entergy"),
        ("VST", "Vistra"),
        ("XEL", "Xcel Energy"),
        ("EXC", "Exelon"),
        ("ED", "Consolidated Edison"),
        ("PEG", "Public Service Enterprise Group"),
        ("PCG", "PG&E"),
        ("WEC", "WEC Energy Group"),
        ("DTE", "DTE Energy"),
        ("AEE", "Ameren"),
        ("NRG", "NRG Energy"),
        ("ATO", "Atmos Energy"),
        ("EIX", "Edison International"),
    ),
    "Real Estate": _constituents(
        ("WELL", "Welltower"),
        ("PLD", "Prologis"),
        ("EQIX", "Equinix"),
        ("AMT", "American Tower"),
        ("SPG", "Simon Property Group"),
        ("DLR", "Digital Realty Trust"),
        ("O", "Realty Income"),
        ("VTR", "Ventas"),
        ("PSA", "Public Storage"),
        ("CBRE", "CBRE Group"),
        ("IRM", "Iron Mountain"),
        ("CCI", "Crown Castle"),
        ("EXR", "Extra Space Storage"),
        ("VICI", "VICI Properties"),
        ("AVB", "AvalonBay Communities"),
        ("EQR", "Equity Residential"),
        ("SBAC", "SBA Communications"),
        ("ESS", "Essex Property Trust"),
        ("KIM", "Kimco Realty"),
        ("WY", "Weyerhaeuser"),
    ),
    "Basic Materials": _constituents(
        ("LIN", "Linde"),
        ("NEM", "Newmont"),
        ("FCX", "Freeport-McMoRan"),
        ("CTVA", "Corteva"),
        ("SHW", "Sherwin-Williams"),
        ("APD", "Air Products and Chemicals"),
        ("ECL", "Ecolab"),
        ("VMC", "Vulcan Materials"),
        ("CRH", "CRH"),
        ("MLM", "Martin Marietta Materials"),
        ("NUE", "Nucor"),
        ("STLD", "Steel Dynamics"),
        ("PPG", "PPG Industries"),
        ("SW", "Smurfit Westrock"),
        ("DOW", "Dow"),
        ("IFF", "International Flavors & Fragrances"),
        ("PKG", "Packaging Corporation of America"),
        ("AMCR", "Amcor"),
        ("IP", "International Paper"),
        ("DD", "DuPont"),
    ),
    "Crypto": _constituents(
        ("COIN", "Coinbase Global"),
        ("MSTR", "Strategy"),
        ("IREN", "IREN"),
        ("MARA", "MARA Holdings"),
        ("GLXY", "Galaxy Digital"),
        ("CIFR", "Cipher Mining"),
        ("FIGR", "Figure Technology Solutions"),
        ("BMNR", "BitMine Immersion Technologies"),
        ("WULF", "TeraWulf"),
        ("HUT", "Hut 8"),
        ("RIOT", "Riot Platforms"),
        ("CRCL", "Circle Internet Group"),
        ("CLSK", "CleanSpark"),
        ("KEEL", "Keel Infrastructure"),
        ("HOOD", "Robinhood Markets"),
        ("ETOR", "eToro Group"),
        ("BTDR", "Bitdeer Technologies"),
        ("MELI", "MercadoLibre"),
        ("V", "Visa"),
        ("MA", "Mastercard"),
    ),
    "Metals": _constituents(
        ("LEU", "Centrus Energy"),
        ("HL", "Hecla Mining"),
        ("UEC", "Uranium Energy"),
        ("CDE", "Coeur Mining"),
        ("NEM", "Newmont"),
        ("RGLD", "Royal Gold"),
        ("FCX", "Freeport-McMoRan"),
        ("MP", "MP Materials"),
        ("RS", "Reliance"),
        ("USAR", "USA Rare Earth"),
        ("NUE", "Nucor"),
        ("CNR", "Core Natural Resources"),
        ("MTRN", "Materion"),
        ("HCC", "Warrior Met Coal"),
        ("STLD", "Steel Dynamics"),
        ("CMC", "Commercial Metals"),
        ("BTU", "Peabody Energy"),
        ("CENX", "Century Aluminum"),
        ("CLF", "Cleveland-Cliffs"),
        ("AA", "Alcoa"),
    ),
}


def sectors_page_symbols(sector: str) -> list[str]:
    return [constituent.symbol for constituent in SECTORS_PAGE_DATA.get(sector, ())]


def sectors_page_unique_symbols() -> list[str]:
    return sorted(
        {
            constituent.symbol
            for constituents in SECTORS_PAGE_DATA.values()
            for constituent in constituents
        }
    )
